### ISSUE TITLE
Missing instructions for reproducibility

### ISSUE THREAD

**Issue by sloede** [trixi-framework/paper-2023-es_two_layer#1]
This repo already looks like it's in great shape! From a cursory look, it seems like there are two pieces of information missing for full reproducibility:

1. The users need to be instructed to always start Julia such that the *project* directory is set to `code/`
2. Before the first execution of any file, the packages need to be installed, e.g., by running
   ```shell
   julia --project=code/ -e 'using Pkg; Pkg.instantiate()'
   ```

**Comment by patrickersing** [comment]
Thanks for the input! 
I do not mention this specifically in the README.md, but the project is instantiated automatically when running the test cases with the run-scripts that are provided in each subfolder. The specific commands are contained within the 
[two_layer.jl](https://github.com/trixi-framework/paper-2023-es_two_layer/blob/v1.0.3/code/two_layer.jl) file, which is called in each run-script. So when following the provided instructions the results can already be reproduced without executing any further commands.
I still think its a good addition to include these instructions if users want to execute any individual julia files. I therefore added your suggestion to the [README.md](https://github.com/trixi-framework/paper-2023-es_two_layer/blob/v1.0.3/code/README.md) in c46fd2948ac78ba4f223d5724863f15483b90a6c.

**Comment by sloede** [comment]
Great, sounds good!
